# GET http://localhost:5000/api/cars
###
GET http://localhost:5000/api/cars/feature-categories
###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"Volkswagen Passat B7",
    "body":"Седан",
    "drive":"Передній",
    "transmission":"Автомат",
    "fuel":"Бензин",
    "engineCapacity":2,
    "horsepower":176.8,
    "mileage":168,
    "manufactureYear":2018
    // real price: 14999
}

###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"Honda CR-V",
    "body":"Позашляховик / Кросовер",
    "drive":"Повний",
    "transmission":"Автомат",
    "fuel":"Газ / Бензин",
    "engineCapacity":2.4,
    "horsepower":299.2,
    "mileage":162,
    "manufactureYear":2008,
    // real price: 12999
}

###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"Volkswagen Golf VII",
    "body":"Унiверсал",
    "drive":"Передній",
    "transmission":"Ручна / Механіка",
    "fuel":"Дизель",
    "engineCapacity":1.6,
    "horsepower":110,
    "mileage":236,
    "manufactureYear":2014
    // real price: 11800
}

###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"Mazda 6",
    "body":"Седан",
    "drive":"Передній",
    "transmission":"Ручна / Механіка",
    "fuel":"Газ / Бензин",
    "engineCapacity":2,
    "horsepower":147,
    "mileage":202,
    "manufactureYear":2006
    // real price: 6200
}

###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"BMW X5",
    "body":"Позашляховик / Кросовер",
    "drive":"Повний",
    "transmission":"Автомат",
    "fuel":"Дизель",
    "engineCapacity":2,
    "horsepower":314,
    "mileage":5,
    "manufactureYear":2016
    // real price: 55000
}

###
POST http://localhost:5000/api/cars/predict
content-type: application/json

{
    "model":"Audi A8",
    "body":"Седан",
    "drive":"Повний",
    "transmission":"Автомат",
    "fuel":"Дизель",
    "engineCapacity":3,
    "horsepower":262.48,
    "mileage":77,
    "manufactureYear":2016
    // real price: 52000
}

###
GET http://localhost:5000/api/cars/train/10